
GET http://localhost:1919/run-scraper-continente?produto=Whiskey

GET http://localhost:1919/run-scraper-pingodoce?produto=Whiskey

GET http://localhost:1919/run-scraper-auchan?produto=Whiskey

GET http://localhost:1919/run-scraper-lidl?produto=arroz

GET http://localhost:1919/run-scraper-lidl?produto=maionese



GET https://supersave.pt/web/api/v2/getCategoryProducts.php?category=Macarronete HTTP/1.1

POST https://www.imperiodobrasil.pt/customer/create
Content-Type: application/x-www-form-urlencoded

customer[email]=dsada@gmail.com&customer[password]=sadsad&commit=Entrar

cntrl+alt+r para rodar a req